# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sc-core-ext}
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin MacKenzie IV"]
  s.date = %q{2011-02-24}
  s.description = %q{A collection of core extensions that I have come to rely on in more than one package}
  s.email = %q{sinisterchipmunk@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "History.txt",
    "LICENSE",
    "Manifest.txt",
    "PostInstall.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/sc-core-ext.rb",
    "lib/sc-core-ext/active_support/ordered_hash.rb",
    "lib/sc-core-ext/array.rb",
    "lib/sc-core-ext/date_time.rb",
    "lib/sc-core-ext/dependencies.rb",
    "lib/sc-core-ext/float.rb",
    "lib/sc-core-ext/hash.rb",
    "lib/sc-core-ext/numeric.rb",
    "lib/sc-core-ext/object.rb",
    "lib/sc-core-ext/regexp.rb",
    "lib/sc-core-ext/string.rb",
    "script/console",
    "script/destroy",
    "script/generate",
    "spec/rcov.opts",
    "spec/sc-core-ext/active_support/ordered_hash_spec.rb",
    "spec/sc-core-ext/array_spec.rb",
    "spec/sc-core-ext/date_time_spec.rb",
    "spec/sc-core-ext/float_spec.rb",
    "spec/sc-core-ext/hash_spec.rb",
    "spec/sc-core-ext/numeric_spec.rb",
    "spec/sc-core-ext/object_spec.rb",
    "spec/sc-core-ext/regexp_spec.rb",
    "spec/sc-core-ext/string_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/sinisterchipmunk/sc-core-ext}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{A collection of core extensions that I have come to rely on in more than one package}
  s.test_files = [
    "spec/sc-core-ext/active_support/ordered_hash_spec.rb",
    "spec/sc-core-ext/array_spec.rb",
    "spec/sc-core-ext/date_time_spec.rb",
    "spec/sc-core-ext/float_spec.rb",
    "spec/sc-core-ext/hash_spec.rb",
    "spec/sc-core-ext/numeric_spec.rb",
    "spec/sc-core-ext/object_spec.rb",
    "spec/sc-core-ext/regexp_spec.rb",
    "spec/sc-core-ext/string_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<rcov>, [">= 0.9.8"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<rcov>, [">= 0.9.8"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<rcov>, [">= 0.9.8"])
  end
end

